name: metarbolomics
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.7,<3.9
  - matchms >=0.9.2
  - pandas
  - scipy
  - numpy
  - tensorflow
  - ipykernel
